@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Junior User",
    "email": "junior@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "junioruser@gmail.com",
    "password": "123456"
}

###

# @name create_ticket
POST {{baseUrl}}/tickets
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Teste III",
    "description": "Quero encerrar o contrato!",
    "propertyId": "4755ea25-6463-48b6-ad37-6b23e3eb8241"
}

###

# @name create_message_ticket
POST {{baseUrl}}/messages
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "message": "irraaaaaa!", 
    "ticketId": "7fea0e84-4e3f-4458-8b3a-53cd8a3b4858"
}

###

# @name fetch_recent_ticket
GET {{baseUrl}}/tickets
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_property
POST {{baseUrl}}/properties
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Casa D", 
    "address": "R. Iolanda Rodrigues Sobral, 6 - Iputinga, Recife - PE",
    "type": "HOUSE"
}

###

# @name delete_property
DELETE  {{baseUrl}}/properties/4755ea25-6463-48b6-ad37-6b23e3eb8241
Content-Type: application/json
Authorization: Bearer {{authToken}}

###